[package]
name = "rusty_weather_prediction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forecast = "3.0.0"
reqwest = "0.10.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }