[package]
name = "rusty_weather_prediction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weather-reports = "0.1.5"
codespan-reporting = "0.11.1"